import {
  Alpine,
  AmericanFootball,
  Archery,
  Athletics,
  AussieRules,
  AustralianFootball,
  Badminton,
  Bandy,
  Baseball,
  Basketball,
  Basketball3x3,
  BeachSoccer,
  BeachVolley,
  Biathlon,
  Bobsleigh,
  Bowls,
  Boxing,
  Canoeing,
  Chess,
  Cricket,
  CrossCountrySkiing,
  Curling,
  Cycling,
  Darts,
  Diving,
  EBasketball,
  EFootball,
  EIceHockey,
  Equestrian,
  EsportCounterStrike,
  EsportDota,
  ESportsPlus,
  ETableTennis,
  Fencing,
  FieldHockey,
  FigureSkating,
  FinancialBetting,
  Floorball,
  FlyingOdds,
  FreestyleSkiing,
  Futsal,
  Gaa,
  GaelicFootball,
  GaelicHurling,
  Golf,
  Greyhounds,
  Gymnastics,
  Handball,
  HorseRacing,
  IceHockey,
  Judo,
  Kabaddi,
  KironHorses,
  KironMotorRacing,
  KironTableTennis,
  Lacrosse,
  LeagueOfLegends,
  Lotto,
  Luge,
  Manual,
  MarathonSwimming,
  Mma,
  ModernPentathlon,
  Motorsport,
  Netball,
  NordicCombined,
  Olympics,
  Other,
  Padel,
  Pesapallo,
  PriceBoosts,
  Rowing,
  Rugby,
  Sailing,
  ShortTrackSpeedSkating,
  Skateboarding,
  Skeleton,
  SkiJumping,
  Snooker,
  Snowboarding,
  Soccer,
  SoccerSpecials,
  Specials,
  SpeedSkating,
  Speedway,
  Squash,
  Starcraft,
  Surf,
  Surfing,
  Swimming,
  TableTennis,
  Taekwondo,
  Tennis,
  TrackCycling,
  Triathlon,
  Turf,
  Vbi,
  Vci,
  Vfec,
  Vflm,
  Volleyball,
  Waterpolo,
  Weightlifting,
  Wintersports,
  Wrestling,
} from '../sports'

export enum SportsIds {
  SOCCER = 1,
  HORSE_RACING = 2,
  GREYHOUNDS = 3,
  TENNIS = 4,
  RUGBY = 5,
  SNOOKER = 6,
  MOTORSPORT = 7,
  GAA = 8,
  DARTS = 9,
  BOXING = 11,
  BASKETBALL = 12,
  BASEBALL = 13,
  CYCLING = 14,
  GOLF = 15,
  ICE_HOCKEY = 16,
  HANDBALL = 17,
  FLOORBALL = 18,
  VOLLEYBALL = 19,
  AMERICAN_FOOTBALL = 20,
  WINTER_SPORTS = 21,
  BANDY = 22,
  FUTSAL = 23,
  CURLING = 25,
  AUSSIE_RULES = 26,
  WATERPOLO = 27,
  ATHLETICS = 28,
  CRICKET = 31,
  AUSTRALIAN_FOOTBALL = 32,
  BEACH_VOLLEY = 33,
  TABLE_TENNIS = 34,
  BADMINTON = 35,
  SWIMMING = 37,
  ALPINE = 38,
  CROSS_COUNTRY_SKIING = 39,
  MMA = 40,
  SKI_JUMPING = 41,
  FREESTYLE_SKIING = 42,
  BIATHLON = 43,
  BOBSLEIGH = 44,
  LUGE = 45,
  FIGURE_SKATING = 46,
  NORDIC_COMBINED = 47,
  SHORT_TRACK_SPEED_SKATING = 48,
  SPEED_SKATING = 49,
  SKELETON = 50,
  SNOWBOARDING = 51,
  ROWING = 52,
  SAILING = 53,
  TAEKWONDO = 54,
  GYMNASTICS = 55,
  SPEEDWAY = 56,
  REFERENCE_SPORT = 57,
  CANOEING = 58,
  TRACK_CYCLING = 59,
  FENCING = 60,
  WRESTLING = 61,
  ARCHERY = 62,
  BEACH_SOCCER = 63,
  BOWLS = 64,
  PESAPALLO = 65,
  E_SPORTS = 66,
  SURF = 67,
  TURF = 68,
  SQUASH = 69,
  ESPORT_COUNTER_STRIKE = 70,
  LEAGUE_OF_LEGENDS = 71,
  ESPORT_DOTA = 72,
  STARCRAFT = 73,
  FIELD_HOCKEY = 74,
  UNASSIGNED_SPORT = 79,
  SOCCER_SPECIALS = 80,
  BASKETBALL_3X3 = 81,
  RUGBY_LEAGUE = 82,
  SPECIALS = 90,
  VFL = 100,
  VHC = 101,
  VDR = 102,
  VTO = 103,
  VBL = 104,
  VFEC = 105,
  PRICE_BOOSTS = 121,
  LOTTO = 150,
  CHESS = 159,
  GAELIC_FOOTBALL = 192,
  GAELIC_HURLING = 193,
  KABADDI = 195,
  VTI = 206,
  VBI = 208,
  VMR = 209,
  VTT = 210,
  VCI = 211,
  NETBALL = 215,
  LACROSSE = 217,
  PADEL = 220,
  MANUAL = 300,
  FLYING_ODDS = 301,
  SOFTBALL = 302,
  BMX_RACING = 303,
  MOUNTAIN_BIKE = 304,
  OFF_ROAD = 305,
  DIVING = 306,
  EQUESTRAIN = 307,
  SKATEBOARDING = 308,
  SURFING = 309,
  TRIATHLON = 310,
  WEIGHTLIFTING = 311,
  OLYMPICS = 312,
  MARATHON_SWIMMING = 313,
  JUDO = 314,
  MODERN_PENTATHLON = 315,
  FINANCIAL_BETS = 316,
  E_FOOTBALL = 318,
  E_ICE_HOCKEY = 319,
  E_BASKETBALL = 320,
}

export const sportsIcon = {
  [SportsIds.AMERICAN_FOOTBALL]: AmericanFootball,
  [SportsIds.ALPINE]: Alpine,
  [SportsIds.ARCHERY]: Archery,
  [SportsIds.ATHLETICS]: Athletics,
  [SportsIds.AUSSIE_RULES]: AussieRules,
  [SportsIds.AUSTRALIAN_FOOTBALL]: AustralianFootball,
  [SportsIds.BADMINTON]: Badminton,
  [SportsIds.BANDY]: Bandy,
  [SportsIds.BASEBALL]: Baseball,
  [SportsIds.BOXING]: Boxing,
  [SportsIds.BASKETBALL]: Basketball,
  [SportsIds.BASKETBALL_3X3]: Basketball3x3,
  [SportsIds.BEACH_SOCCER]: BeachSoccer,
  [SportsIds.BEACH_VOLLEY]: BeachVolley,
  [SportsIds.BIATHLON]: Biathlon,
  [SportsIds.BOBSLEIGH]: Bobsleigh,
  [SportsIds.BOWLS]: Bowls,
  [SportsIds.CANOEING]: Canoeing,
  [SportsIds.CHESS]: Chess,
  [SportsIds.CRICKET]: Cricket,
  [SportsIds.CURLING]: Curling,
  [SportsIds.CYCLING]: Cycling,
  [SportsIds.CROSS_COUNTRY_SKIING]: CrossCountrySkiing,
  [SportsIds.DARTS]: Darts,
  [SportsIds.DIVING]: Diving,
  [SportsIds.E_SPORTS]: ESportsPlus,
  [SportsIds.E_BASKETBALL]: EBasketball,
  [SportsIds.EQUESTRAIN]: Equestrian,
  [SportsIds.E_FOOTBALL]: EFootball,
  [SportsIds.ESPORT_DOTA]: EsportDota,
  [SportsIds.E_ICE_HOCKEY]: EIceHockey,
  [SportsIds.ESPORT_COUNTER_STRIKE]: EsportCounterStrike,
  [SportsIds.FENCING]: Fencing,
  [SportsIds.FUTSAL]: Futsal,
  [SportsIds.FIELD_HOCKEY]: FieldHockey,
  [SportsIds.FLOORBALL]: Floorball,
  [SportsIds.FIGURE_SKATING]: FigureSkating,
  [SportsIds.FINANCIAL_BETS]: FinancialBetting,
  [SportsIds.FREESTYLE_SKIING]: FreestyleSkiing,
  [SportsIds.FLYING_ODDS]: FlyingOdds,
  [SportsIds.JUDO]: Judo,
  [SportsIds.ICE_HOCKEY]: IceHockey,
  [SportsIds.GAA]: Gaa,
  [SportsIds.GOLF]: Golf,
  [SportsIds.GREYHOUNDS]: Greyhounds,
  [SportsIds.GAELIC_FOOTBALL]: GaelicFootball,
  [SportsIds.GAELIC_HURLING]: GaelicHurling,
  [SportsIds.GYMNASTICS]: Gymnastics,
  [SportsIds.HANDBALL]: Handball,
  [SportsIds.HORSE_RACING]: HorseRacing,
  [SportsIds.KABADDI]: Kabaddi,
  [SportsIds.MANUAL]: Manual,
  [SportsIds.MMA]: Mma,
  [SportsIds.MARATHON_SWIMMING]: MarathonSwimming,
  [SportsIds.MOTORSPORT]: Motorsport,
  [SportsIds.MODERN_PENTATHLON]: ModernPentathlon,
  [SportsIds.MOUNTAIN_BIKE]: Other,
  [SportsIds.NETBALL]: Netball,
  [SportsIds.LACROSSE]: Lacrosse,
  [SportsIds.LOTTO]: Lotto,
  [SportsIds.LUGE]: Luge,
  [SportsIds.LEAGUE_OF_LEGENDS]: LeagueOfLegends,
  [SportsIds.OFF_ROAD]: Other,
  [SportsIds.OLYMPICS]: Olympics,
  [SportsIds.PADEL]: Padel,
  [SportsIds.PESAPALLO]: Pesapallo,
  [SportsIds.PRICE_BOOSTS]: PriceBoosts,
  [SportsIds.REFERENCE_SPORT]: Other,
  [SportsIds.ROWING]: Rowing,
  [SportsIds.RUGBY]: Rugby,
  [SportsIds.RUGBY_LEAGUE]: Rugby,
  [SportsIds.SOCCER]: Soccer,
  [SportsIds.SAILING]: Sailing,
  [SportsIds.SNOOKER]: Snooker,
  [SportsIds.SHORT_TRACK_SPEED_SKATING]: ShortTrackSpeedSkating,
  [SportsIds.SURF]: Surf,
  [SportsIds.SKATEBOARDING]: Skateboarding,
  [SportsIds.SKELETON]: Skeleton,
  [SportsIds.SKI_JUMPING]: SkiJumping,
  [SportsIds.SNOWBOARDING]: Snowboarding,
  [SportsIds.SOCCER_SPECIALS]: SoccerSpecials,
  [SportsIds.SOFTBALL]: Other,
  [SportsIds.SPECIALS]: Specials,
  [SportsIds.SPEED_SKATING]: SpeedSkating,
  [SportsIds.SPEEDWAY]: Speedway,
  [SportsIds.SQUASH]: Squash,
  [SportsIds.STARCRAFT]: Starcraft,
  [SportsIds.SURFING]: Surfing,
  [SportsIds.SWIMMING]: Swimming,
  [SportsIds.TABLE_TENNIS]: TableTennis,
  [SportsIds.TENNIS]: Tennis,
  [SportsIds.TURF]: Turf,
  [SportsIds.TAEKWONDO]: Taekwondo,
  [SportsIds.TRIATHLON]: Triathlon,
  [SportsIds.TRACK_CYCLING]: TrackCycling,
  [SportsIds.UNASSIGNED_SPORT]: Other,
  [SportsIds.VBI]: Vbi,
  [SportsIds.VBL]: Other,
  [SportsIds.VCI]: Vci,
  [SportsIds.VDR]: Other,
  [SportsIds.VFL]: Vflm,
  [SportsIds.VFEC]: Vfec,
  [SportsIds.VHC]: KironHorses,
  [SportsIds.VMR]: KironMotorRacing,
  [SportsIds.VOLLEYBALL]: Volleyball,
  [SportsIds.VTO]: Other,
  [SportsIds.VTT]: ETableTennis,
  [SportsIds.VTI]: KironTableTennis,
  [SportsIds.WATERPOLO]: Waterpolo,
  [SportsIds.WINTER_SPORTS]: Wintersports,
  [SportsIds.WEIGHTLIFTING]: Weightlifting,
  [SportsIds.WRESTLING]: Wrestling,
  [SportsIds.NORDIC_COMBINED]: NordicCombined,
  [SportsIds.BMX_RACING]: Other,
}
