# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  pull_request:
    types: [ closed, opened ]
    branches:
      - main
      - 'feature/**'

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          cypress: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        env:
          CHROMATIC_ARCHIVE_LOCATION=./custom/dir
